// backend/behavior/models/BehaviorIncident.js
//
// The core append-only record (brief §1, §6). ONE document per incident, ever
// — never an update-in-place — so six teachers logging at once cannot collide,
// and the student's count is simply an aggregation across all of these rows.
// This is the single most important property of the system: incidents
// aggregate PER STUDENT across ALL teachers, never per-teacher.
//
// `behaviorSnapshot` freezes the behaviour + consequence wording at log time so
// later edits to the behaviour definition don't rewrite history (brief §5a).

import mongoose from "mongoose";

const BehaviorIncidentSchema = new mongoose.Schema(
  {
    schoolId: { type: mongoose.Schema.Types.ObjectId, ref: "BehaviorSchool", required: true, index: true },
    studentId: { type: mongoose.Schema.Types.ObjectId, ref: "BehaviorStudent", required: true, index: true },
    // The teacher who logged it (membership id). Any teacher, any student.
    teacherId: { type: mongoose.Schema.Types.ObjectId, ref: "BehaviorTeacher", required: true, index: true },
    behaviorId: { type: mongoose.Schema.Types.ObjectId, ref: "Behavior", required: true },

    // Frozen copy of the behaviour at the moment of logging (edit-safe history).
    behaviorSnapshot: {
      name: { type: String, default: "" },
      description: { type: String, default: "" },
      triggerMode: { type: String, enum: ["THRESHOLD", "IMMEDIATE"], default: "THRESHOLD" },
      consequenceText: { type: String, default: "" },
    },

    detailText: { type: String, default: "" }, // optional free-text detail
    // Convenience flag mirroring the snapshot trigger mode at log time.
    immediateFlag: { type: Boolean, default: false },

    // When a notice fires, the incidents that fed it are marked so they are not
    // re-counted toward the next threshold (history is kept, count is reset).
    countedInNoticeId: { type: mongoose.Schema.Types.ObjectId, ref: "BehaviorNotice", default: null, index: true },

    // Set when this incident was auto-generated by a missed-consequence
    // escalation (Phase 2, brief §8b) rather than logged by a teacher.
    systemGenerated: { type: Boolean, default: false },

    // Append-only: we store an explicit timestamp (defaults to now) rather than
    // relying solely on createdAt, so back-dated imports stay possible.
    timestamp: { type: Date, default: () => new Date(), index: true },
  },
  { timestamps: true }
);

// Hot path: counting a student's recent incidents.
BehaviorIncidentSchema.index({ studentId: 1, timestamp: -1 });

export default mongoose.models.BehaviorIncident || mongoose.model("BehaviorIncident", BehaviorIncidentSchema);
