// backend/routes/stocksAdvice.js
//
// POST /api/stocks-advice
//   Body: {}  (uses your stored portfolio + risk profile)
//   Headers: Authorization: Bearer <sessionToken>
//
// Returns structured advice generated by Claude with live web-search.
// Falls back to a clear error if ANTHROPIC_API_KEY isn't configured.
//
// Response shape:
//   { generatedAt, advice: [{ sev, title, body, meta }, ...], sources: [{title,url},...] }
//
// Notes:
// - Uses the Anthropic Messages API with the `web_search_20250305` tool
//   (server-side tool — no separate news API key needed).
// - Auth is the same HMAC session token used by /api/stocks-portfolio.

import express from "express";
import crypto from "crypto";
import StocksPortfolio from "../models/StocksPortfolio.js";
import StocksAdviceRec from "../models/StocksAdviceRec.js";

const router = express.Router();

// ── token verification (same scheme as stocksPortfolio.js) ────────
function getSecret() {
  return process.env.STOCKS_SECRET || process.env.MEDICENTRE_SECRET || "";
}
function b64urlDecode(s) {
  s = String(s || "").replace(/-/g, "+").replace(/_/g, "/");
  while (s.length % 4) s += "=";
  return Buffer.from(s, "base64");
}
function b64url(buf) {
  return buf.toString("base64").replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}
function verifySessionToken(token) {
  const secret = getSecret();
  if (!secret) return null;
  const [body, sig] = String(token || "").split(".");
  if (!body || !sig) return null;
  const expected = b64url(crypto.createHmac("sha256", secret).update(body).digest());
  if (sig.length !== expected.length) return null;
  try {
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
  } catch { return null; }
  try {
    const payload = JSON.parse(b64urlDecode(body).toString("utf8"));
    if (payload?.sub !== "stocks-session") return null;
    if (typeof payload?.exp !== "number" || payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch { return null; }
}
function requireStocksAuth(req, res, next) {
  const a = req.headers?.authorization || req.headers?.Authorization || "";
  const token = typeof a === "string" && a.startsWith("Bearer ") ? a.slice(7).trim() : null;
  if (!token) return res.status(401).json({ error: "Missing Authorization bearer token" });
  const payload = verifySessionToken(token);
  if (!payload) return res.status(401).json({ error: "Invalid or expired session" });
  req.stocksUser = { email: payload.email.toLowerCase() };
  next();
}

// ── helpers ────────────────────────────────────────────────────────
function aggregateByTicker(positions, fx) {
  const m = {};
  for (const p of positions) {
    const val =
      p.ccy === "USD"
        ? (p.priceCad ?? (p.priceUsd ? p.priceUsd * fx : 0)) * (p.qty || 0)
        : (p.priceCad || 0) * (p.qty || 0);
    if (!m[p.ticker]) m[p.ticker] = { ticker: p.ticker, qty: 0, cad: 0 };
    m[p.ticker].qty += p.qty || 0;
    m[p.ticker].cad += val;
  }
  return Object.values(m).sort((a, b) => b.cad - a.cad);
}

function portfolioSummary(profile) {
  const fx = profile.fxUsdCad || 1.37;
  const agg = aggregateByTicker(profile.positions || [], fx);
  const total = agg.reduce((s, a) => s + a.cad, 0);
  const lines = agg.map(
    (a) => `${a.ticker}: ${a.qty.toLocaleString()} sh  ≈ $${Math.round(a.cad).toLocaleString()} CAD  (${total > 0 ? ((a.cad / total) * 100).toFixed(1) : "0"}%)`
  );
  return { total, agg, text: lines.join("\n") };
}

function buildPrompt(profile, summary) {
  const risk = profile.riskTolerance || "aggressive";
  const today = new Date().toISOString().slice(0, 10);
  return `You are Richard's personal stock advisor. Today is ${today}.

His risk tolerance: ${risk}.
Total portfolio (CAD): ~$${Math.round(summary.total).toLocaleString()}.

Holdings:
${summary.text}

Use the web_search tool to pull the latest news on the top 6 holdings (and any names that appear in recent material news flow). Then write 4–7 advice cards as a JSON array. Each card MUST have:

  - "sev": one of "danger" | "warn" | "good" | "info"
  - "title": short headline (under 90 chars)
  - "body": 2–4 sentences. Every actionable recommendation MUST follow this exact format with all four levels:
       Action: BUY/SELL/TRIM/HOLD <N> sh <TICKER>. Entry: $X (or "$X-$Y" zone). Target: $Y (timeframe). Stop: $Z. Horizon: <weeks/months>.
     NEVER write "at market", "current levels", or "now" as the Entry — always give a specific price or tight zone. If you want him to wait for a dip, give the dip price. If you want him to buy at the prevailing price, write that exact price.
     For "hold" calls, state the trigger that would change the call.
  - "meta": one-line supporting fact (price moves, news date, position size)

Severity rules:
- "danger" — concentration risk above 30%, thesis-break news, severe drawdown
- "warn"   — sector overhangs, earnings misses, watchlist breakouts
- "good"   — confirming positive catalysts
- "info"   — general context, non-urgent ideas

Always include at least one "new cash deployment" card with tiers $500 / $1,000 / $5,000 / $10,000. Each tier MUST contain explicit BUY recs in the format above, each with an Entry price/zone, Target, Stop, and Horizon. Never write "deploy into NVDA" without specifying the entry price you want him to pay. Tilt new-cash ideas AWAY from existing concentration.

Return ONLY valid JSON: { "advice": [...], "sources": [{"title":"...","url":"..."}] }
No prose outside the JSON.`;
}

// Parse a trade recommendation line out of a card body.
// Looks for:
//   Action: BUY 40 sh ENB. Entry: $75. Target: $84. Stop: $69. Horizon: 12 months
// Returns null if no actionable rec is present in the body.
function parseRec(body) {
  if (!body || typeof body !== "string") return null;
  const m = body.match(/Action:\s*(BUY|SELL|TRIM|HOLD)\s*(\d[\d,]*)?\s*(?:sh)?\s*([A-Z][A-Z0-9.\-]{0,15})\b[^.]*?(?:Entry:\s*\$?([\d.]+))?[^.]*?(?:Target:\s*\$?([\d.]+))?[^.]*?(?:Stop:\s*\$?([\d.]+))?[^.]*?(?:Horizon:\s*([^.\n]+))?/i);
  if (!m) return null;
  const [, action, sharesStr, ticker, entry, target, stop, horizon] = m;
  const shares = sharesStr ? parseInt(sharesStr.replace(/,/g, ""), 10) : null;
  // Derive horizon days
  let horizonDays = 30;
  if (horizon) {
    const h = horizon.toLowerCase();
    const num = parseInt(h.match(/(\d+)/)?.[1] || "0", 10) || 1;
    if (h.includes("day")) horizonDays = num;
    else if (h.includes("week")) horizonDays = num * 7;
    else if (h.includes("month")) horizonDays = num * 30;
    else if (h.includes("year")) horizonDays = num * 365;
  }
  return {
    action: action.toUpperCase(),
    shares,
    ticker: ticker.toUpperCase(),
    entryPrice: entry ? parseFloat(entry) : null,
    targetPrice: target ? parseFloat(target) : null,
    stopPrice: stop ? parseFloat(stop) : null,
    horizonDays,
  };
}

// Fetch current price for a ticker via the in-process price proxy
async function fetchCurrentPrice(ticker) {
  try {
    const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1d&range=1d`;
    const ctrl = new AbortController();
    const tid = setTimeout(() => ctrl.abort(), 5000);
    const r = await fetch(url, { signal: ctrl.signal, headers: { "User-Agent": "Mozilla/5.0 (Curriculate)" } });
    clearTimeout(tid);
    if (!r.ok) return null;
    const j = await r.json();
    return j?.chart?.result?.[0]?.meta?.regularMarketPrice ?? null;
  } catch { return null; }
}

// Compute hypothetical P&L on a recommendation given the current price.
// Sign convention: positive = the call was right.
function scorePnl(rec, currentPrice) {
  if (!rec.entryPrice || !currentPrice) return null;
  const raw = (currentPrice - rec.entryPrice) / rec.entryPrice;
  // SELL/TRIM: profit if price went DOWN
  if (rec.action === "SELL" || rec.action === "TRIM") return -raw;
  // BUY: profit if price went UP
  if (rec.action === "BUY") return raw;
  // HOLD: not directional, so 0 — we don't credit or debit holds
  return 0;
}

// Strip Claude web_search citation markers from model output.
// Web_search results include inline <cite index="...">...</cite> wrappers
// that we don't want appearing in advice card bodies — citations are
// returned separately as the `sources` array.
function stripCiteTags(s) {
  if (!s) return s;
  return s
    .replace(/<cite[^>]*>([\s\S]*?)<\/cite>/gi, "$1")
    .replace(/<\/?cite[^>]*>/gi, "")
    // also strip any stray Anthropic search-result reference markers
    .replace(/\[(?:cite[:_]?)?\d+(?:[-,]\d+)*\]/g, "");
}

// Extract first balanced JSON object from a string
function extractJson(text) {
  if (!text) return null;
  // strip code fences if present
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) { try { return JSON.parse(fenced[1]); } catch {} }
  // find first { and last }
  const first = text.indexOf("{");
  const last = text.lastIndexOf("}");
  if (first === -1 || last === -1 || last <= first) return null;
  try { return JSON.parse(text.slice(first, last + 1)); } catch { return null; }
}

// ── handler ────────────────────────────────────────────────────────
router.post("/", requireStocksAuth, async (req, res) => {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return res.status(503).json({
        error:
          "AI advice not configured: set ANTHROPIC_API_KEY in environment to enable news-aware advice.",
      });
    }

    const profile = await StocksPortfolio.findOne({ email: req.stocksUser.email }).lean();
    if (!profile || !profile.positions?.length) {
      return res.status(400).json({ error: "No positions to advise on." });
    }

    const summary = portfolioSummary(profile);
    const prompt = buildPrompt(profile, summary);

    // Anthropic Messages API call with web_search server-side tool
    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.STOCKS_ADVICE_MODEL || "claude-sonnet-4-5",
        max_tokens: 4096,
        tools: [{ type: "web_search_20250305", name: "web_search", max_uses: 8 }],
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!r.ok) {
      const errBody = await r.text().catch(() => "");
      console.error("Anthropic error:", r.status, errBody.slice(0, 500));
      return res.status(502).json({ error: `Anthropic API ${r.status}: ${errBody.slice(0, 200)}` });
    }
    const j = await r.json();

    // Collect text blocks (Anthropic returns content[] mixed with tool_use/tool_result)
    const textOut = stripCiteTags(
      (j?.content || [])
        .filter((b) => b.type === "text")
        .map((b) => b.text)
        .join("\n")
    );

    // Collect web_search citations as sources
    const sources = [];
    for (const b of j?.content || []) {
      if (b.type === "text" && Array.isArray(b.citations)) {
        for (const c of b.citations) {
          if (c?.url && !sources.find((s) => s.url === c.url)) {
            sources.push({ title: c.title || c.url, url: c.url });
          }
        }
      }
    }

    const parsed = extractJson(textOut);
    if (!parsed || !Array.isArray(parsed.advice)) {
      return res.status(502).json({
        error: "AI returned unparseable response",
        raw: textOut.slice(0, 800),
      });
    }

    // Defense-in-depth: also strip cite tags from each card's text fields
    // in case Claude embedded them inside the JSON payload itself.
    for (const card of parsed.advice) {
      if (card.title) card.title = stripCiteTags(card.title);
      if (card.body) card.body = stripCiteTags(card.body);
      if (card.meta) card.meta = stripCiteTags(card.meta);
    }

    // Persist parsed recommendations so we can compute "if-followed" P&L later
    const generatedAt = new Date();
    const recsToSave = [];
    for (const card of parsed.advice) {
      const rec = parseRec(card.body);
      if (rec && rec.entryPrice && rec.action !== "HOLD") {
        recsToSave.push({
          email: req.stocksUser.email,
          generatedAt,
          source: "ai",
          ...rec,
          rationale: (card.title || "") + " — " + (card.body || "").slice(0, 400),
        });
      }
    }
    if (recsToSave.length) {
      StocksAdviceRec.insertMany(recsToSave).catch((e) =>
        console.warn("advice-rec save warning:", e?.message)
      );
    }

    res.json({
      generatedAt: generatedAt.toISOString(),
      advice: parsed.advice,
      sources: parsed.sources?.length ? parsed.sources : sources,
      tracked: recsToSave.length,
    });
  } catch (err) {
    console.error("stocks-advice error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

// ─────────────────────────────────────────────────────────────────────
// GET /api/stocks-advice/performance?days=30
//
// Computes "if you had followed every recommendation from the last N days,
// what would your hypothetical P&L be?" — averaged across all recs.
// Returns rollups for 7d / 14d / 30d (or whatever the caller passes).
// ─────────────────────────────────────────────────────────────────────
router.get("/performance", requireStocksAuth, async (req, res) => {
  try {
    const windows = [7, 14, 30];
    const now = Date.now();

    const recs = await StocksAdviceRec.find({
      email: req.stocksUser.email,
      generatedAt: { $gte: new Date(now - 31 * 86400 * 1000) },
    }).lean();

    if (recs.length === 0) {
      return res.json({
        windows: windows.map((d) => ({ days: d, recCount: 0, avgPnlPct: null, hitRate: null })),
        recent: [],
      });
    }

    // Fetch current prices (deduped) for scoring
    const tickers = [...new Set(recs.map((r) => r.ticker))];
    const priceMap = {};
    await Promise.all(
      tickers.map(async (t) => {
        priceMap[t] = await fetchCurrentPrice(t);
      })
    );

    const scored = recs.map((r) => {
      const cur = priceMap[r.ticker];
      const pnl = scorePnl(r, cur);
      return { ...r, currentPrice: cur, pnlPct: pnl };
    });

    // Persist score back to the rec for future reference
    Promise.all(
      scored.map((s) =>
        StocksAdviceRec.updateOne(
          { _id: s._id },
          { $set: { lastScoredAt: new Date(), lastScoredPrice: s.currentPrice, lastPnlPct: s.pnlPct } }
        ).catch(() => null)
      )
    ).catch(() => null);

    const rollups = windows.map((d) => {
      const cutoff = now - d * 86400 * 1000;
      const window = scored.filter((s) => new Date(s.generatedAt).getTime() >= cutoff && s.pnlPct != null);
      if (window.length === 0) return { days: d, recCount: 0, avgPnlPct: null, hitRate: null };
      const avg = window.reduce((acc, s) => acc + s.pnlPct, 0) / window.length;
      const hits = window.filter((s) => s.pnlPct > 0).length;
      return {
        days: d,
        recCount: window.length,
        avgPnlPct: avg * 100, // already a fraction; convert to percent
        hitRate: (hits / window.length) * 100,
      };
    });

    res.json({
      windows: rollups,
      recent: scored
        .sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt))
        .slice(0, 20)
        .map((s) => ({
          ticker: s.ticker,
          action: s.action,
          entryPrice: s.entryPrice,
          currentPrice: s.currentPrice,
          targetPrice: s.targetPrice,
          stopPrice: s.stopPrice,
          horizonDays: s.horizonDays,
          generatedAt: s.generatedAt,
          pnlPct: s.pnlPct != null ? s.pnlPct * 100 : null,
        })),
    });
  } catch (err) {
    console.error("stocks-advice performance error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

export default router;
