// backend/routes/stocksAdvice.js
//
// POST /api/stocks-advice
//   Body: {}  (uses your stored portfolio + risk profile)
//   Headers: Authorization: Bearer <sessionToken>
//
// Returns structured advice generated by Claude with live web-search.
// Falls back to a clear error if ANTHROPIC_API_KEY isn't configured.
//
// Response shape:
//   { generatedAt, advice: [{ sev, title, body, meta }, ...], sources: [{title,url},...] }
//
// Notes:
// - Uses the Anthropic Messages API with the `web_search_20250305` tool
//   (server-side tool — no separate news API key needed).
// - Auth is the same HMAC session token used by /api/stocks-portfolio.

import express from "express";
import crypto from "crypto";
import StocksPortfolio from "../models/StocksPortfolio.js";
import StocksAdviceRec from "../models/StocksAdviceRec.js";
import StocksTradeJournal from "../models/StocksTradeJournal.js";
import {
  generateBriefing,
  emailBriefing,
  md2html,
  parseRecsFromBriefing,
  monitorOpenRecs,
} from "../jobs/stocksDailyBriefing.js";
import { getTechnicals, formatTechnicalsLine } from "../services/stocksTechnicals.js";
import { getFundamentals, formatFundamentalsLine } from "../services/stocksFundamentals.js";
import { getMacroContext, formatMacroBlock } from "../services/stocksMacroContext.js";
import { computeLifecycle, formatLifecycleBlock } from "../services/stocksLifecycle.js";
import { computeFactorTilts, formatFactorBlock } from "../services/stocksFactorAnalysis.js";

const router = express.Router();

// ── token verification (same scheme as stocksPortfolio.js) ────────
function getSecret() {
  return process.env.STOCKS_SECRET || process.env.MEDICENTRE_SECRET || "";
}
function b64urlDecode(s) {
  s = String(s || "").replace(/-/g, "+").replace(/_/g, "/");
  while (s.length % 4) s += "=";
  return Buffer.from(s, "base64");
}
function b64url(buf) {
  return buf.toString("base64").replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}
function verifySessionToken(token) {
  const secret = getSecret();
  if (!secret) return null;
  const [body, sig] = String(token || "").split(".");
  if (!body || !sig) return null;
  const expected = b64url(crypto.createHmac("sha256", secret).update(body).digest());
  if (sig.length !== expected.length) return null;
  try {
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
  } catch { return null; }
  try {
    const payload = JSON.parse(b64urlDecode(body).toString("utf8"));
    if (payload?.sub !== "stocks-session") return null;
    if (typeof payload?.exp !== "number" || payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch { return null; }
}
function requireStocksAuth(req, res, next) {
  const a = req.headers?.authorization || req.headers?.Authorization || "";
  const token = typeof a === "string" && a.startsWith("Bearer ") ? a.slice(7).trim() : null;
  if (!token) return res.status(401).json({ error: "Missing Authorization bearer token" });
  const payload = verifySessionToken(token);
  if (!payload) return res.status(401).json({ error: "Invalid or expired session" });
  req.stocksUser = { email: payload.email.toLowerCase() };
  next();
}

// ── helpers ────────────────────────────────────────────────────────
function aggregateByTicker(positions, fx) {
  const m = {};
  for (const p of positions) {
    const val =
      p.ccy === "USD"
        ? (p.priceCad ?? (p.priceUsd ? p.priceUsd * fx : 0)) * (p.qty || 0)
        : (p.priceCad || 0) * (p.qty || 0);
    if (!m[p.ticker]) m[p.ticker] = { ticker: p.ticker, qty: 0, cad: 0 };
    m[p.ticker].qty += p.qty || 0;
    m[p.ticker].cad += val;
  }
  return Object.values(m).sort((a, b) => b.cad - a.cad);
}

function portfolioSummary(profile) {
  const fx = profile.fxUsdCad || 1.37;
  const agg = aggregateByTicker(profile.positions || [], fx);
  const total = agg.reduce((s, a) => s + a.cad, 0);

  // Determine each ticker's native trading currency + last-known native price.
  // Used to render prices in the SAME currency Richard trades them in.
  const nativeCcy = {};
  const nativePrice = {};
  for (const p of profile.positions || []) {
    if (!nativeCcy[p.ticker]) {
      nativeCcy[p.ticker] = p.ccy;
      nativePrice[p.ticker] = p.ccy === "USD" ? p.priceUsd : p.priceCad;
    }
  }

  const lines = agg.map((a) => {
    const ccy = nativeCcy[a.ticker] || "USD";
    const px = nativePrice[a.ticker];
    const pxStr = px ? `@ $${px.toFixed(2)} ${ccy}` : "";
    const pctStr = total > 0 ? `(${((a.cad / total) * 100).toFixed(1)}%)` : "";
    return `${a.ticker} (${ccy}): ${a.qty.toLocaleString()} sh ${pxStr} ≈ $${Math.round(a.cad).toLocaleString()} CAD ${pctStr}`;
  });

  // Per-currency cash totals across all accounts
  let cashUsd = 0, cashCad = 0;
  const perAccountCash = [];
  for (const a of profile.accounts || []) {
    cashUsd += a.cashUsd || 0;
    cashCad += a.cashCad || 0;
    if ((a.cashUsd || 0) > 0 || (a.cashCad || 0) > 0) {
      perAccountCash.push(`  ${a.name}: $${(a.cashCad || 0).toFixed(0)} CAD, $${(a.cashUsd || 0).toFixed(0)} USD`);
    }
  }
  const cashCadEquiv = cashCad + cashUsd * fx;

  return { total, agg, text: lines.join("\n"), cashUsd, cashCad, cashCadEquiv, perAccountCash };
}

// Signals checklist — what the AI MUST search for and incorporate
const SIGNALS_CHECKLIST = `
Mandatory signals to search and weigh for each top-holding before writing recs:

A. NEWS — corporate, regulatory, M&A, leadership changes (last 24h)
B. PERIODIC REPORTING — next earnings date (flag if within 14d), most recent EPS/revenue vs consensus, guidance changes
C. CORPORATE ACTIONS — ex-dividend dates within 14d, dividend changes, splits, spin-offs (DJT's Truth Social spin-off is live)
D. ANALYST ACTION — upgrades/downgrades from top-tier shops in last 7d, price-target moves >10%, new coverage
E. INSIDER + OWNERSHIP — Form 4 buys/sells last 30d (cluster patterns), 13F shifts (Berkshire/Buffett etc.), short interest changes (>20% of float)
F. TECHNICAL / FLOW — 50d/200d MA, golden/death crosses, RSI <30 or >70, unusual options flow, volume vs 20-day average
G. MACRO — Fed/BoC commentary, oil moves (ENB/SU/CNQ), USD/CAD, VIX level

Make 6-10 web_search calls covering these categories. For EACH actionable rec, cite at least one specific signal from above that drives the call.
`;

// Canadian tax + account-placement guidance
const CANADIAN_TAX_BLOCK = `
Account-placement & tax notes (Canadian investor):
- Eligible Canadian-corp dividends (ENB, BCE, TD, RY, BNS, T, CNQ, SU, etc.) receive the Canadian dividend tax credit in non-registered accounts. ENB's ~6% yield is materially more tax-efficient than headline.
- US dividend stocks held in an RRSP are EXEMPT from US 15% withholding under the Canada–US tax treaty. In TFSA or Non-Spousal, withholding applies (recoverable only in Non-Spousal as a foreign tax credit).
- TFSA: tax-free capital gains — best home for high-conviction, high-volatility growth bets (NVDA, PLTR, RKLB).
- Non-Spousal: capital gains at 50% inclusion; losses are harvestable. Avoid US dividend payers here.
- For every BUY rec, suggest the specific account (Non-Spousal / RRSP / TFSA) using these rules.
`;

// Pre-compute quant signals (FMP fundamentals + local technicals) for the
// top-N tickers in a portfolio. Run in parallel, tolerate per-ticker failure.
export async function computeQuantSignals(profile, topN = 8) {
  const fx = profile.fxUsdCad || 1.37;
  const agg = aggregateByTicker(profile.positions || [], fx).slice(0, topN);
  const tickerInfo = {};
  for (const p of profile.positions || []) {
    if (!tickerInfo[p.ticker]) tickerInfo[p.ticker] = { ccy: p.ccy };
  }
  const out = {};
  await Promise.all(
    agg.map(async (a) => {
      const ccy = tickerInfo[a.ticker]?.ccy || "USD";
      const [tech, fund] = await Promise.all([
        getTechnicals(a.ticker).catch(() => ({ ok: false })),
        getFundamentals(a.ticker, ccy).catch(() => ({ ok: false })),
      ]);
      out[a.ticker] = { tech, fund, ccy };
    })
  );
  return out;
}

function formatQuantSignalsBlock(quantSignals) {
  if (!quantSignals || Object.keys(quantSignals).length === 0) return "";
  const lines = [];
  for (const [ticker, sig] of Object.entries(quantSignals)) {
    lines.push(`${ticker} (${sig.ccy}):`);
    lines.push(`  Fundamentals: ${formatFundamentalsLine(sig.fund)}`);
    lines.push(`  Technicals:   ${formatTechnicalsLine(sig.tech)}`);
  }
  return `\nQUANT SIGNALS PER HOLDING (pre-computed — use THESE numbers, don't guess from search results):\n${lines.join("\n")}\n`;
}

function buildPrompt(profile, summary, monitorAlerts = [], quantSignals = null, macro = null, lifecycle = null, factors = null) {
  const risk = profile.riskTolerance || "aggressive";
  const today = new Date().toISOString().slice(0, 10);
  const commission = Number(profile.commissionPerTrade ?? 9.95);
  const fxSpread = Number(profile.fxSpreadPct ?? 1.5);
  const fx = Number(profile.fxUsdCad || 1.37);

  // Per-account cash inventory — surfaced ONCE here in a hard-to-miss block
  const accountCashTable = (profile.accounts || [])
    .map(a => `  ${a.name}: $${(a.cashCad || 0).toFixed(0)} CAD · $${(a.cashUsd || 0).toFixed(0)} USD`)
    .join("\n") || "  (no accounts configured)";

  // Planned withdrawals — must-have cash by date that constrains recs
  const pending = (profile.plannedWithdrawals || [])
    .map(w => {
      const days = Math.max(0, Math.round((new Date(w.targetDate).getTime() - Date.now()) / 86400000));
      const accountName = w.account ? (profile.accounts.find(a => a.id === w.account)?.name || w.account) : null;
      return `  $${w.amount.toFixed(0)} ${w.currency} in ${days}d${accountName ? ` from ${accountName}` : ""}${w.notes ? ` · ${w.notes}` : ""}`;
    });
  const plannedWithdrawalsBlock = pending.length
    ? `\nPLANNED WITHDRAWALS (cash that MUST be available by target date — recommendations must avoid locking it up):\n${pending.join("\n")}\n`
    : "";

  const orderTicketBlock = `
ORDER-TICKET GUIDANCE (gap-protection — every BUY/SELL rec must include this):
- Equity recommendations execute at OPEN by default if not specified, which exposes the trade to overnight gap moves.
- For EVERY BUY or SELL/TRIM rec, include an "Order ticket" line specifying:
  • Order type: LIMIT (preferred — protects against unfavorable opens) vs MARKET (only when fill certainty matters more than price, e.g., stop-out)
  • Limit price (in the security's native currency)
  • Duration: "Day" (default — cancels EOD) or "GTC" (good-til-cancelled, fine for stop-losses)
- Sizing the limit:
  • BUY: limit price = upper end of entry zone, or current ask + small buffer (~0.3% for liquid names, ~1% for thinly-traded). Never higher than the rec's target.
  • SELL: limit price = lower end of desired exit zone, or current bid − small buffer. Never lower than the rec's stop level.
- For BUY recs, ALWAYS add an "After fill" line recommending a STOP-LOSS SELL order to enter once the buy executes:
  • Stop price = the rec's Stop level
  • Order type: STOP-LIMIT (avoid pure STOP-MARKET in case of flash-crash slippage). Limit = stop − 1-2%.
  • Duration: GTC

Example format inside the rec body:

  Action: BUY 40 sh ENB. Entry: $75-$76 CAD. Target: $84 CAD (12mo). Stop: $69 CAD. Horizon: 12 months.
  Order ticket: LIMIT BUY 40 ENB @ $76.00 CAD max, Day order. (Caps price; protects vs gap-up.)
  After fill: GTC STOP-LIMIT SELL 40 ENB, stop $69.00 / limit $68.00 CAD. (Auto-protects downside.)
  Source: RRSP CAD sub · uses $3,040 of $4,500 CAD available.
  Cost note: commission ~$6.95 per order = ~$13.90 total (entry + stop). FX impact: none.

For "swap" recs (sell one, buy another), the SELL leg also needs a LIMIT SELL ticket so a gap-down doesn't dump shares cheap.
`;

  const priceCurrencyBlock = `
PRICE CURRENCY CONVENTION (strict — applies to every rec, alert, and discussion):
- Every position has a native trading currency shown in the Holdings list (e.g., "TSLA (USD)" trades in USD, "ENB (CAD)" trades in CAD).
- When stating a price for a security, use its NATIVE currency only.
  ✓ "TSLA at $442" or "TSLA at $442 USD"
  ✗ "TSLA at $607 CAD" — NEVER convert US-listed stock prices to CAD for price discussion
  ✓ "ENB at $75.58" or "ENB at $75.58 CAD"
- For Entry/Target/Stop in trade recs: use the SECURITY's native currency, never the converted one.
- A CAD or USD conversion in parentheses is ONLY appropriate when discussing portfolio TOTALS or sizing math (e.g., "Uses ~$10,640 USD ≈ $14,600 CAD of available cash"), not when stating a security's price.
`;

  const tradingCostsBlock = `
Real-world trading-cost frictions (factor these into every rec):
- Commission: $${commission.toFixed(2)} per trade (each BUY and each SELL counts separately; a Swap = 2 commissions = $${(commission * 2).toFixed(2)})
- FX spread on USD↔CAD conversion: ~${fxSpread}% one-way (round-trip ${(fxSpread * 2).toFixed(1)}%)
- Current FX rate: ${fx.toFixed(3)} USD/CAD

Per-account cash inventory (CRITICAL — read this carefully):
${accountCashTable}
${plannedWithdrawalsBlock}

Sizing rules:
- Reject trades where commissions exceed 1% of gross trade value (~$${(commission * 100).toFixed(0)} minimum). If a rec falls below that, upsize, batch in the same currency, or say "wait for more cash."
- For USD↔CAD swaps, the round-trip FX drag is ~${(fxSpread * 2).toFixed(1)}% — name this drag in the rec and only recommend if expected upside exceeds it materially.
- PREFER trades that don't require currency conversion.

WITHDRAWAL-AWARE SIZING (if PLANNED WITHDRAWALS block above is non-empty):
- For each planned withdrawal: the listed currency × amount MUST be available as CASH by the target date.
- Subtract planned withdrawals from "deployable cash" before sizing any BUY rec. If a planned withdrawal is in 30 days for $5K USD and current USD cash is $1K, the AI has $0 deployable USD (not $1K).
- If cash is short, recommend SPECIFIC TRIMS by date Y to raise the needed cash. Prefer trims of losers, concentration excesses, or names with thesis-already-played-out.
- Do NOT recommend long-horizon BUYs (>30 days) using cash that's needed sooner.
- Flag any planned withdrawal whose cash isn't on track in a "danger" advice card.

ACCOUNT-SOURCE RULE (mandatory — no exceptions):
- Every BUY recommendation MUST name a single source account (Non-Spousal / RRSP / TFSA).
- The trade size MUST fit within THAT account's cash balance in the trade's currency. Look at the per-account inventory above. Do NOT propose sizes that exceed any single account's bucket.
- NEVER recommend trades that would require:
  * Cross-account transfers (e.g., "move $2,000 from RRSP to TFSA then buy")
  * Splitting one buy across multiple accounts
  * Pooling cash from two accounts
- If the tax-optimal account (per Canadian tax block) doesn't have enough cash, do ONE of:
  (a) Recommend a smaller size that fits the tax-optimal account's actual balance
  (b) Recommend the trade in a different account that DOES have the cash, and explicitly note the tax tradeoff ("Ideal in TFSA but only $400 USD there; using RRSP USD instead — you lose tax-free growth on the gain, gain treaty exemption on dividends")
  (c) Recommend ADDING cash to the preferred account first via Deposit, then buying once funded
- Every BUY rec must include a "Source" line: "Source: RRSP · uses $X of $Y CAD/USD available in that account."
- Every BUY rec must include a "Cost note" line: "Commission ~$${commission.toFixed(2)}, FX impact: <none / X% drag>".
`;

  const alertsBlock = monitorAlerts.length
    ? `\n⚠️ OPEN-RECOMMENDATION ALERTS (computed deterministically — surface these prominently as a dedicated card at the TOP of the advice list, severity "warn" or "danger"):\n${monitorAlerts.map(a => `- ${a}`).join("\n")}\n`
    : "";

  // Cash section — drives the deployment recommendations
  const hasCash = summary.cashUsd > 5 || summary.cashCad > 5;
  const cashBlock = hasCash
    ? `\nAvailable cash on hand:
  $${summary.cashCad.toFixed(2)} CAD
  $${summary.cashUsd.toFixed(2)} USD
  Total ≈ $${Math.round(summary.cashCadEquiv).toLocaleString()} CAD at FX ${(profile.fxUsdCad || 1.37).toFixed(3)}
${summary.perAccountCash.length ? "Per account:\n" + summary.perAccountCash.join("\n") : ""}
`
    : `\nAvailable cash on hand: $0 (no cash to deploy).\n`;

  const cashInstructions = hasCash
    ? `Richard has CASH READY TO DEPLOY (see above). You MUST include a "Cash deployment — using existing cash" card with concrete BUY recs sized to actually use that cash. Compute share counts from the cash budget at the proposed Entry price.

Example format if he has $2,500 CAD and $500 USD:
  Action: BUY 30 sh ENB. Entry: $74.80 CAD (current $75.58). Target: $84 CAD (12mo). Stop: $69. Horizon: 12 months.
    Uses ~$2,244 CAD of $2,500 CAD available.
  Action: BUY 3 sh NVDA. Entry: $130 USD (on a pullback; current $134). Target: $200 USD (12mo). Stop: $108. Horizon: 12 months.
    Uses ~$390 USD of $500 USD available.

Do NOT recommend more spending than the cash he has. Don't suggest fractional shares. If the cash in a currency is too small for any reasonable buy (< $200 in that currency), say so and suggest pooling or FX-converting.`
    : `Richard has no cash available to deploy right now. Do NOT recommend new BUYs unless they can be funded by TRIMming an existing position you explicitly call out in the same card (e.g., "Trim DJT for $X CAD, redeploy to ENB"). Otherwise focus on hold/trim/watch-list calls.`;

  return `You are Richard's personal stock advisor — operating at senior-analyst level. Today is ${today}.

His risk tolerance: ${risk}.

SENIOR-ANALYST EXPECTATIONS (read carefully — what separates this from generic LLM advice):
1. Always reason from the MACRO REGIME block down to the rec. A growth-pick recommendation that ignores high VIX + rising rates is junior work.
2. Always anchor stops on ATR (the technicals block has a 2.5×ATR suggested stop per ticker). Flat percentage stops are wrong — they get tagged on noise in volatile names and leave too much room in calm names.
3. Always reference per-position cost basis from the LIFECYCLE block. A SELL of a winner has a tax cost; a SELL of a loser unlocks tax savings. Acknowledge it.
4. Surface TAX-LOSS HARVEST candidates when applicable — they're literally free money in non-registered accounts. If the LIFECYCLE block lists any TLH candidates, mention them.
5. Cite SPECIFIC numbers from the pre-computed signal blocks, not vague descriptions. "RSI 32" not "looks oversold." "P/E 87" not "looks expensive." "2.5×ATR stop at $407" not "8% stop."
Total portfolio (CAD): ~$${Math.round(summary.total).toLocaleString()} ← FOR YOUR REFERENCE ONLY. DO NOT echo this aggregate dollar figure in the advice cards. Use percentages, % of book, and per-position values, but never the total portfolio dollar amount.

Holdings:
${summary.text}
${cashBlock}
${alertsBlock}
${formatMacroBlock(macro)}
${formatFactorBlock(factors)}
${formatLifecycleBlock(lifecycle)}
${formatQuantSignalsBlock(quantSignals)}
${priceCurrencyBlock}
${orderTicketBlock}
${tradingCostsBlock}
${CANADIAN_TAX_BLOCK}
${SIGNALS_CHECKLIST}

Use the web_search tool aggressively (6-10 calls covering the signal categories above). Then write 4–7 advice cards as a JSON array. Each card MUST have:

  - "sev": one of "danger" | "warn" | "good" | "info"
  - "title": short headline (under 90 chars)
  - "body": 2–4 sentences. Every actionable recommendation MUST follow this exact format with all four levels:
       Action: BUY/SELL/TRIM/HOLD <N> sh <TICKER>. Entry: $X (or "$X-$Y" zone). Target: $Y (timeframe). Stop: $Z. Horizon: <weeks/months>.
     NEVER write "at market", "current levels", or "now" as the Entry — always give a specific price or tight zone.
     For "hold" calls, state the trigger that would change the call.
  - "meta": one-line supporting fact (price moves, news date, position size)

Severity rules:
- "danger" — concentration risk above 30%, thesis-break news, severe drawdown
- "warn"   — sector overhangs, earnings misses, watchlist breakouts
- "good"   — confirming positive catalysts, executed cash deployments
- "info"   — general context, non-urgent ideas

CASH DEPLOYMENT INSTRUCTIONS:
${cashInstructions}

Tilt all new BUYs AWAY from existing concentration. Especially do NOT add to DJT, DJTWW, or RUM unless prices are clearly oversold at a specific technical level you can defend.

Return ONLY valid JSON: { "advice": [...], "sources": [{"title":"...","url":"..."}] }
No prose outside the JSON.`;
}

// Parse a trade recommendation line out of a card body.
// Looks for:
//   Action: BUY 40 sh ENB. Entry: $75. Target: $84. Stop: $69. Horizon: 12 months
// Returns null if no actionable rec is present in the body.
function parseRec(body) {
  if (!body || typeof body !== "string") return null;
  const m = body.match(/Action:\s*(BUY|SELL|TRIM|HOLD)\s*(\d[\d,]*)?\s*(?:sh)?\s*([A-Z][A-Z0-9.\-]{0,15})\b[^.]*?(?:Entry:\s*\$?([\d.]+))?[^.]*?(?:Target:\s*\$?([\d.]+))?[^.]*?(?:Stop:\s*\$?([\d.]+))?[^.]*?(?:Horizon:\s*([^.\n]+))?/i);
  if (!m) return null;
  const [, action, sharesStr, tickerRaw, entry, target, stop, horizon] = m;
  // Strip trailing dot — the ticker pattern allows `.` so it greedily captures
  // the sentence-ending period (e.g. "PLTR." instead of "PLTR").
  const ticker = String(tickerRaw || "").toUpperCase().replace(/\.+$/, "");
  const shares = sharesStr ? parseInt(sharesStr.replace(/,/g, ""), 10) : null;
  // Derive horizon days
  let horizonDays = 30;
  if (horizon) {
    const h = horizon.toLowerCase();
    const num = parseInt(h.match(/(\d+)/)?.[1] || "0", 10) || 1;
    if (h.includes("day")) horizonDays = num;
    else if (h.includes("week")) horizonDays = num * 7;
    else if (h.includes("month")) horizonDays = num * 30;
    else if (h.includes("year")) horizonDays = num * 365;
  }
  return {
    action: action.toUpperCase(),
    shares,
    ticker,
    entryPrice: entry ? parseFloat(entry) : null,
    targetPrice: target ? parseFloat(target) : null,
    stopPrice: stop ? parseFloat(stop) : null,
    horizonDays,
  };
}

// Fetch current price for a ticker via the in-process price proxy
async function fetchCurrentPrice(ticker) {
  try {
    const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(ticker)}?interval=1d&range=1d`;
    const ctrl = new AbortController();
    const tid = setTimeout(() => ctrl.abort(), 5000);
    const r = await fetch(url, { signal: ctrl.signal, headers: { "User-Agent": "Mozilla/5.0 (Curriculate)" } });
    clearTimeout(tid);
    if (!r.ok) return null;
    const j = await r.json();
    return j?.chart?.result?.[0]?.meta?.regularMarketPrice ?? null;
  } catch { return null; }
}

// Compute hypothetical P&L on a recommendation given the current price.
// Sign convention: positive = the call was right.
function scorePnl(rec, currentPrice) {
  if (!rec.entryPrice || !currentPrice) return null;
  const raw = (currentPrice - rec.entryPrice) / rec.entryPrice;
  // SELL/TRIM: profit if price went DOWN
  if (rec.action === "SELL" || rec.action === "TRIM") return -raw;
  // BUY: profit if price went UP
  if (rec.action === "BUY") return raw;
  // HOLD: not directional, so 0 — we don't credit or debit holds
  return 0;
}

// Strip Claude web_search citation markers from model output.
// Web_search results include inline <cite index="...">...</cite> wrappers
// that we don't want appearing in advice card bodies — citations are
// returned separately as the `sources` array.
function stripCiteTags(s) {
  if (!s) return s;
  return s
    .replace(/<cite[^>]*>([\s\S]*?)<\/cite>/gi, "$1")
    .replace(/<\/?cite[^>]*>/gi, "")
    // also strip any stray Anthropic search-result reference markers
    .replace(/\[(?:cite[:_]?)?\d+(?:[-,]\d+)*\]/g, "");
}

// Extract first balanced JSON object from a string
function extractJson(text) {
  if (!text) return null;
  // strip code fences if present
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) { try { return JSON.parse(fenced[1]); } catch {} }
  // find first { and last }
  const first = text.indexOf("{");
  const last = text.lastIndexOf("}");
  if (first === -1 || last === -1 || last <= first) return null;
  try { return JSON.parse(text.slice(first, last + 1)); } catch { return null; }
}

// ── handler ────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────
// Shared advice-generation worker. Reused by both /  and /consensus.
// Returns { advice, sources, textOut } where advice is the parsed JSON
// array of cards and sources are the web_search citations.
// ─────────────────────────────────────────────────────────────────────
async function runOneAdvicePass({ profile, monitorAlerts, quantSignals, macro, lifecycle, factors }) {
  const summary = portfolioSummary(profile);
  const prompt = buildPrompt(profile, summary, monitorAlerts, quantSignals, macro, lifecycle, factors);
  const r = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: process.env.STOCKS_ADVICE_MODEL || "claude-sonnet-4-5",
      max_tokens: 4096,
      tools: [{ type: "web_search_20250305", name: "web_search", max_uses: 12 }],
      messages: [{ role: "user", content: prompt }],
    }),
  });
  if (!r.ok) {
    const errBody = await r.text().catch(() => "");
    throw new Error(`Anthropic ${r.status}: ${errBody.slice(0, 200)}`);
  }
  const j = await r.json();
  const textOut = stripCiteTags(
    (j?.content || [])
      .filter((b) => b.type === "text")
      .map((b) => b.text)
      .join("\n")
  );
  const sources = [];
  for (const b of j?.content || []) {
    if (b.type === "text" && Array.isArray(b.citations)) {
      for (const c of b.citations) {
        if (c?.url && !sources.find((s) => s.url === c.url)) {
          sources.push({ title: c.title || c.url, url: c.url });
        }
      }
    }
  }
  const parsed = extractJson(textOut);
  if (!parsed || !Array.isArray(parsed.advice)) {
    throw new Error("AI returned unparseable response");
  }
  for (const card of parsed.advice) {
    if (card.title) card.title = stripCiteTags(card.title);
    if (card.body) card.body = stripCiteTags(card.body);
    if (card.meta) card.meta = stripCiteTags(card.meta);
  }
  return { advice: parsed.advice, sources: parsed.sources?.length ? parsed.sources : sources };
}

router.post("/", requireStocksAuth, async (req, res) => {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return res.status(503).json({
        error:
          "AI advice not configured: set ANTHROPIC_API_KEY in environment to enable news-aware advice.",
      });
    }

    const profile = await StocksPortfolio.findOne({ email: req.stocksUser.email }).lean();
    if (!profile || !profile.positions?.length) {
      return res.status(400).json({ error: "No positions to advise on." });
    }

    const summary = portfolioSummary(profile);

    // Compute all upstream signals in parallel
    const [monitorRes, quantSignals, macro, lifecycle, factors] = await Promise.all([
      monitorOpenRecs(req.stocksUser.email).catch(() => ({ alerts: [] })),
      computeQuantSignals(profile).catch(() => ({})),
      getMacroContext().catch(() => null),
      computeLifecycle(profile).catch(() => null),
      computeFactorTilts(profile).catch(() => null),
    ]);
    const monitorAlerts = monitorRes?.alerts || [];

    const prompt = buildPrompt(profile, summary, monitorAlerts, quantSignals, macro, lifecycle, factors);

    // Anthropic Messages API call with web_search server-side tool
    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: process.env.STOCKS_ADVICE_MODEL || "claude-sonnet-4-5",
        max_tokens: 4096,
        tools: [{ type: "web_search_20250305", name: "web_search", max_uses: 12 }],
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!r.ok) {
      const errBody = await r.text().catch(() => "");
      console.error("Anthropic error:", r.status, errBody.slice(0, 500));
      return res.status(502).json({ error: `Anthropic API ${r.status}: ${errBody.slice(0, 200)}` });
    }
    const j = await r.json();

    // Collect text blocks (Anthropic returns content[] mixed with tool_use/tool_result)
    const textOut = stripCiteTags(
      (j?.content || [])
        .filter((b) => b.type === "text")
        .map((b) => b.text)
        .join("\n")
    );

    // Collect web_search citations as sources
    const sources = [];
    for (const b of j?.content || []) {
      if (b.type === "text" && Array.isArray(b.citations)) {
        for (const c of b.citations) {
          if (c?.url && !sources.find((s) => s.url === c.url)) {
            sources.push({ title: c.title || c.url, url: c.url });
          }
        }
      }
    }

    const parsed = extractJson(textOut);
    if (!parsed || !Array.isArray(parsed.advice)) {
      return res.status(502).json({
        error: "AI returned unparseable response",
        raw: textOut.slice(0, 800),
      });
    }

    // Defense-in-depth: also strip cite tags from each card's text fields
    // in case Claude embedded them inside the JSON payload itself.
    for (const card of parsed.advice) {
      if (card.title) card.title = stripCiteTags(card.title);
      if (card.body) card.body = stripCiteTags(card.body);
      if (card.meta) card.meta = stripCiteTags(card.meta);
    }

    // Persist parsed recommendations so we can compute "if-followed" P&L later.
    // We attach each saved rec's _id back to the card so the FRONTEND can pass
    // it when the user clicks Execute → the trade journal then carries the
    // linkedAdviceRecId and the scorecard knows which recs were followed.
    const generatedAt = new Date();
    const recsToSave = [];
    const recCardIndices = [];
    parsed.advice.forEach((card, idx) => {
      const rec = parseRec(card.body);
      if (rec && rec.entryPrice && rec.action !== "HOLD") {
        recsToSave.push({
          email: req.stocksUser.email,
          generatedAt,
          source: "ai",
          ...rec,
          rationale: (card.title || "") + " — " + (card.body || "").slice(0, 400),
        });
        recCardIndices.push(idx);
      }
    });
    let inserted = [];
    if (recsToSave.length) {
      try {
        inserted = await StocksAdviceRec.insertMany(recsToSave);
      } catch (e) { console.warn("advice-rec save warning:", e?.message); }
    }
    // Attach rec _id back onto its card so the frontend can use it on Execute
    inserted.forEach((doc, i) => {
      const cardIdx = recCardIndices[i];
      if (parsed.advice[cardIdx]) {
        parsed.advice[cardIdx].recId = doc._id.toString();
      }
    });

    res.json({
      generatedAt: generatedAt.toISOString(),
      advice: parsed.advice,
      sources: parsed.sources?.length ? parsed.sources : sources,
      tracked: inserted.length,
    });
  } catch (err) {
    console.error("stocks-advice error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

// ─────────────────────────────────────────────────────────────────────
// GET /api/stocks-advice/performance?days=30
//
// Computes "if you had followed every recommendation from the last N days,
// what would your hypothetical P&L be?" — averaged across all recs.
// Returns rollups for 7d / 14d / 30d (or whatever the caller passes).
// ─────────────────────────────────────────────────────────────────────
router.get("/performance", requireStocksAuth, async (req, res) => {
  try {
    const windows = [7, 14, 30];
    const now = Date.now();

    const recs = await StocksAdviceRec.find({
      email: req.stocksUser.email,
      generatedAt: { $gte: new Date(now - 31 * 86400 * 1000) },
    }).lean();

    if (recs.length === 0) {
      return res.json({
        windows: windows.map((d) => ({ days: d, recCount: 0, avgPnlPct: null, hitRate: null })),
        recent: [],
      });
    }

    // Fetch current prices (deduped) for scoring
    const tickers = [...new Set(recs.map((r) => r.ticker))];
    const priceMap = {};
    await Promise.all(
      tickers.map(async (t) => {
        priceMap[t] = await fetchCurrentPrice(t);
      })
    );

    const scored = recs.map((r) => {
      const cur = priceMap[r.ticker];
      const pnl = scorePnl(r, cur);
      return { ...r, currentPrice: cur, pnlPct: pnl };
    });

    // Persist score back to the rec for future reference
    Promise.all(
      scored.map((s) =>
        StocksAdviceRec.updateOne(
          { _id: s._id },
          { $set: { lastScoredAt: new Date(), lastScoredPrice: s.currentPrice, lastPnlPct: s.pnlPct } }
        ).catch(() => null)
      )
    ).catch(() => null);

    const rollups = windows.map((d) => {
      const cutoff = now - d * 86400 * 1000;
      const window = scored.filter((s) => new Date(s.generatedAt).getTime() >= cutoff && s.pnlPct != null);
      if (window.length === 0) return { days: d, recCount: 0, avgPnlPct: null, hitRate: null };
      const avg = window.reduce((acc, s) => acc + s.pnlPct, 0) / window.length;
      const hits = window.filter((s) => s.pnlPct > 0).length;
      return {
        days: d,
        recCount: window.length,
        avgPnlPct: avg * 100, // already a fraction; convert to percent
        hitRate: (hits / window.length) * 100,
      };
    });

    res.json({
      windows: rollups,
      recent: scored
        .sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt))
        .slice(0, 20)
        .map((s) => ({
          ticker: s.ticker,
          action: s.action,
          entryPrice: s.entryPrice,
          currentPrice: s.currentPrice,
          targetPrice: s.targetPrice,
          stopPrice: s.stopPrice,
          horizonDays: s.horizonDays,
          generatedAt: s.generatedAt,
          pnlPct: s.pnlPct != null ? s.pnlPct * 100 : null,
        })),
    });
  } catch (err) {
    console.error("stocks-advice performance error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

// ─────────────────────────────────────────────────────────────────────
// POST /api/stocks-advice/consensus
//
// Runs the advice generator 3× in parallel. Compares the actionable recs
// across the three runs and bins each as:
//   - "consensus" : same (ticker, action) appears in ≥ 2 of 3 runs
//   - "alternative": appears in only 1 of 3 runs
//
// Returns: { runs: [run1, run2, run3], consensus: [cards], alternatives: [cards] }
//
// Cost note: 3× the per-call cost vs /api/stocks-advice (3× Claude calls,
// 3× web_search budget). Worth it for high-stakes decisions where you want
// to separate signal from sampling noise.
// ─────────────────────────────────────────────────────────────────────
router.post("/consensus", requireStocksAuth, async (req, res) => {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return res.status(503).json({ error: "ANTHROPIC_API_KEY not set on backend" });
    }
    const profile = await StocksPortfolio.findOne({ email: req.stocksUser.email }).lean();
    if (!profile || !profile.positions?.length) {
      return res.status(400).json({ error: "No positions to advise on." });
    }

    // Compute all upstream signals ONCE — shared across all three consensus runs
    const [monitorRes, quantSignals, macro, lifecycle, factors] = await Promise.all([
      monitorOpenRecs(req.stocksUser.email).catch(() => ({ alerts: [] })),
      computeQuantSignals(profile).catch(() => ({})),
      getMacroContext().catch(() => null),
      computeLifecycle(profile).catch(() => null),
      computeFactorTilts(profile).catch(() => null),
    ]);
    const monitorAlerts = monitorRes?.alerts || [];

    // Fan out 3 parallel generations
    const N = 3;
    const settled = await Promise.allSettled(
      Array.from({ length: N }).map(() => runOneAdvicePass({ profile, monitorAlerts, quantSignals, macro, lifecycle, factors }))
    );
    const runs = settled.map((s) => s.status === "fulfilled" ? s.value : { error: s.reason?.message || "Failed", advice: [], sources: [] });
    const successful = runs.filter(r => !r.error);
    if (successful.length < 2) {
      return res.status(502).json({
        error: `Only ${successful.length} of ${N} generations succeeded — consensus needs at least 2.`,
        runs,
      });
    }

    // Match cards across runs by (ticker, action) on the parsed rec inside
    // each card's body. Cards without an actionable Action: line are
    // considered "narrative" and matched by title-similarity instead.
    const fingerprint = (card) => {
      const rec = parseRec(card.body || "");
      if (rec) return `${rec.action}|${rec.ticker}`;
      // Narrative card — use first 60 chars of normalized title
      return "TITLE:" + (card.title || "").toLowerCase().replace(/[^a-z0-9 ]/g, "").trim().slice(0, 60);
    };

    // Tally occurrences across the successful runs
    const tally = new Map(); // fingerprint → { count, cards: [card], runIndices: [i] }
    successful.forEach((run, runIdx) => {
      const seen = new Set();
      for (const card of run.advice) {
        const fp = fingerprint(card);
        if (seen.has(fp)) continue; // de-dup within a run
        seen.add(fp);
        if (!tally.has(fp)) tally.set(fp, { count: 0, cards: [], runIndices: [] });
        const entry = tally.get(fp);
        entry.count++;
        entry.cards.push(card);
        entry.runIndices.push(runIdx);
      }
    });

    const consensus = [];
    const alternatives = [];
    const minConsensus = Math.max(2, Math.ceil(successful.length / 2)); // ≥2 of 2 or ≥2 of 3
    for (const [fp, entry] of tally.entries()) {
      // Pick the longest body version as the canonical (most context)
      const canonical = entry.cards.reduce((best, c) =>
        (c.body || "").length > (best.body || "").length ? c : best, entry.cards[0]);
      const item = {
        ...canonical,
        consensusCount: entry.count,
        totalRuns: successful.length,
        runIndices: entry.runIndices,
      };
      if (entry.count >= minConsensus) consensus.push(item);
      else alternatives.push(item);
    }

    // Sort: consensus by severity (danger > warn > good > info), then count desc
    const sevOrder = { danger: 0, warn: 1, good: 2, info: 3 };
    consensus.sort((a, b) =>
      (sevOrder[a.sev] ?? 9) - (sevOrder[b.sev] ?? 9) || b.consensusCount - a.consensusCount
    );
    alternatives.sort((a, b) => (sevOrder[a.sev] ?? 9) - (sevOrder[b.sev] ?? 9));

    // Persist consensus recs only (so we don't triple-count for the scorecard)
    const generatedAt = new Date();
    const recsToSave = [];
    const consensusIndexMap = [];
    consensus.forEach((card, idx) => {
      const rec = parseRec(card.body || "");
      if (rec && rec.entryPrice && rec.action !== "HOLD") {
        recsToSave.push({
          email: req.stocksUser.email,
          generatedAt,
          source: "ai",
          ...rec,
          rationale: `[Consensus ${card.consensusCount}/${card.totalRuns}] ${card.title || ""} — ${(card.body || "").slice(0, 360)}`,
        });
        consensusIndexMap.push(idx);
      }
    });
    let inserted = [];
    if (recsToSave.length) {
      try { inserted = await StocksAdviceRec.insertMany(recsToSave); } catch (e) {
        console.warn("consensus rec save warning:", e?.message);
      }
    }
    inserted.forEach((doc, i) => {
      const consensusIdx = consensusIndexMap[i];
      if (consensus[consensusIdx]) consensus[consensusIdx].recId = doc._id.toString();
    });

    // Merge sources from all runs, de-duped
    const sourceSet = new Map();
    for (const run of successful) {
      for (const s of run.sources || []) {
        if (!sourceSet.has(s.url)) sourceSet.set(s.url, s);
      }
    }

    res.json({
      generatedAt: generatedAt.toISOString(),
      runs: runs.length,
      runsSucceeded: successful.length,
      consensus,
      alternatives,
      sources: [...sourceSet.values()],
      tracked: inserted.length,
    });
  } catch (err) {
    console.error("consensus error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

// ─────────────────────────────────────────────────────────────────────
// POST /api/stocks-advice/send-briefing
//
// Generates the same briefing the daily cron would generate, optionally
// emails it, and returns the rendered HTML + markdown for preview.
//
// Body: { send?: boolean, to?: string }
//   send  — if true, also email it via Resend. Default false (preview only).
//   to    — override recipient (defaults to the authenticated user's email).
// ─────────────────────────────────────────────────────────────────────
router.post("/send-briefing", requireStocksAuth, async (req, res) => {
  try {
    const profile = await StocksPortfolio.findOne({ email: req.stocksUser.email }).lean();
    if (!profile || !profile.positions?.length) {
      return res.status(400).json({ error: "No portfolio with positions found." });
    }

    // Two paths:
    //   1) PREVIEW (send=false) — always generates fresh briefing
    //   2) SEND (send=true) — if client provides the markdown it just previewed,
    //      reuse it instead of generating again (avoids 30s wait + ensures the
    //      email matches the preview character-for-character).
    const wantsSend = !!req.body?.send;
    const providedMarkdown = typeof req.body?.markdown === "string" && req.body.markdown.trim();
    const reuse = wantsSend && providedMarkdown;

    let markdown;
    let tracked = 0;

    if (reuse) {
      markdown = req.body.markdown;
    } else {
      if (!process.env.ANTHROPIC_API_KEY) {
        return res.status(503).json({ error: "ANTHROPIC_API_KEY not set on backend" });
      }
      markdown = await generateBriefing(profile);

      // Track recommendations only on fresh generations (so we don't re-insert
      // them when the client is just sending a previously-previewed briefing).
      const recs = parseRecsFromBriefing(markdown);
      if (recs.length) {
        StocksAdviceRec.insertMany(
          recs.map((r) => ({
            email: profile.email,
            generatedAt: new Date(),
            source: "ai",
            ...r,
            rationale: "On-demand briefing",
          }))
        ).catch((e) => console.warn("brief-recs save warning:", e?.message));
        tracked = recs.length;
      }
    }

    const subject = `Daily briefing — ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`;
    const inner = md2html(markdown);
    const html = `<!DOCTYPE html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,system-ui,Roboto,Helvetica,Arial,sans-serif;max-width:720px;margin:0 auto;padding:32px 28px;line-height:1.65;color:#1f2937;background:#fafbff;-webkit-font-smoothing:antialiased">${inner}<hr style="border:none;border-top:1px solid #e4e8ef;margin:32px 0 12px"><div style="font-size:11px;color:#9ca3af;line-height:1.5">Research and education only. Not licensed investment advice. Generated by Stocks Advisor at curriculate.net/stocks.</div></body></html>`;

    // Email it if requested
    let sent = false;
    let sendError = null;
    if (wantsSend) {
      const to = (typeof req.body?.to === "string" && req.body.to.trim()) || profile.email;
      try {
        await emailBriefing({ to, subject, md: markdown });
        sent = true;
      } catch (e) {
        sendError = e?.message || String(e);
      }
    }

    res.json({ markdown, html, subject, sent, sendError, tracked, reused: !!reuse });
  } catch (err) {
    console.error("send-briefing error:", err);
    res.status(500).json({ error: err?.message || "Internal error" });
  }
});

// ─────────────────────────────────────────────────────────────────────
// GET /api/stocks-advice/scorecard?days=30
//
// For each rec in the window:
//   - Is there a trade journal entry with linkedAdviceRecId == rec._id?
//     → if yes: "followed". Compute realized/unrealized P&L from cost.
//     → if no:  "skipped". Compute hypothetical P&L (would-have-been).
//   - What's the rec's current status? (open / target-hit / stop-hit)
//
// Aggregates: count of followed vs skipped, total $ P&L attributable to
// advice taken, opportunity cost of advice skipped.
// ─────────────────────────────────────────────────────────────────────
router.get("/scorecard", requireStocksAuth, async (req, res) => {
  try {
    const days = Math.min(Math.max(parseInt(req.query.days, 10) || 30, 7), 365);
    const since = new Date(Date.now() - days * 86400 * 1000);

    const [recs, trades] = await Promise.all([
      StocksAdviceRec.find({ email: req.stocksUser.email, generatedAt: { $gte: since } }).lean(),
      StocksTradeJournal.find({ email: req.stocksUser.email, executedAt: { $gte: since } }).lean(),
    ]);

    if (recs.length === 0) {
      return res.json({
        days,
        summary: { total: 0, followed: 0, skipped: 0, pending: 0,
                   followedPnlPct: null, skippedPnlPct: null,
                   netDollarsFromFollowed: 0, netDollarsFromSkipped: 0 },
        items: [],
      });
    }

    // Build a quick lookup: rec _id (string) → trade journal entry
    const tradesByRecId = new Map();
    for (const t of trades) {
      if (t.linkedAdviceRecId) tradesByRecId.set(String(t.linkedAdviceRecId), t);
    }

    // Fetch current prices once per unique ticker
    const tickers = [...new Set(recs.map(r => r.ticker).filter(Boolean))];
    const priceMap = {};
    await Promise.all(tickers.map(async t => { priceMap[t] = await fetchCurrentPrice(t); }));

    const items = [];
    let followedCount = 0, skippedCount = 0, pendingCount = 0;
    let followedPnlAcc = 0, followedDollars = 0;
    let skippedPnlAcc = 0, skippedDollars = 0;

    for (const rec of recs) {
      const linkedTrade = tradesByRecId.get(String(rec._id));
      const currentPrice = priceMap[rec.ticker];
      const followed = !!linkedTrade;

      // Hypothetical P&L: how the rec WOULD have performed (entry → current)
      // - BUY rec: gain if price went UP from entry
      // - SELL/TRIM rec: gain if price went DOWN from entry (sell was right)
      let hypoPnlPct = null, hypoDollars = null;
      if (rec.entryPrice && currentPrice) {
        const raw = (currentPrice - rec.entryPrice) / rec.entryPrice;
        const dir = (rec.action === "BUY") ? 1 : (rec.action === "SELL" || rec.action === "TRIM") ? -1 : 0;
        hypoPnlPct = dir * raw * 100;
        if (rec.shares) {
          hypoDollars = dir * (currentPrice - rec.entryPrice) * rec.shares;
        }
      }

      // Actual P&L if followed: use the actual fill price from the trade
      let actualPnlPct = null, actualDollars = null;
      if (followed && currentPrice) {
        const leg = (linkedTrade.legs || []).find(l => l.ticker === rec.ticker);
        if (leg && leg.pricePerShare) {
          const raw = (currentPrice - leg.pricePerShare) / leg.pricePerShare;
          const dir = (leg.side === "BUY") ? 1 : -1;
          actualPnlPct = dir * raw * 100;
          actualDollars = dir * (currentPrice - leg.pricePerShare) * (leg.shares || 0);
        }
      }

      // Categorize
      if (followed) {
        followedCount++;
        if (actualPnlPct != null) {
          followedPnlAcc += actualPnlPct;
          followedDollars += actualDollars || 0;
        }
      } else {
        // Skipped: outcome based on hypothetical
        skippedCount++;
        if (hypoPnlPct != null) {
          skippedPnlAcc += hypoPnlPct;
          skippedDollars += hypoDollars || 0;
        }
      }

      items.push({
        recId: String(rec._id),
        generatedAt: rec.generatedAt,
        ticker: rec.ticker,
        action: rec.action,
        shares: rec.shares,
        entryPrice: rec.entryPrice,
        targetPrice: rec.targetPrice,
        stopPrice: rec.stopPrice,
        currentPrice,
        status: rec.status || "open",
        followed,
        hypoPnlPct,
        hypoDollars,
        actualPnlPct,
        actualDollars,
        tradeFillPrice: followed ? (linkedTrade.legs?.[0]?.pricePerShare || null) : null,
        tradeShares: followed ? (linkedTrade.legs?.[0]?.shares || null) : null,
        tradeExecutedAt: followed ? linkedTrade.executedAt : null,
      });
    }

    items.sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt));

    res.json({
      days,
      summary: {
        total: recs.length,
        followed: followedCount,
        skipped: skippedCount,
        pending: pendingCount,
        followRate: recs.length > 0 ? (followedCount / recs.length) * 100 : 0,
        avgFollowedPnlPct: followedCount > 0 ? followedPnlAcc / followedCount : null,
        avgSkippedPnlPct: skippedCount > 0 ? skippedPnlAcc / skippedCount : null,
        netDollarsFromFollowed: followedDollars,
        netDollarsFromSkipped: skippedDollars,
      },
      items,
    });
  } catch (err) {
    console.error("scorecard error:", err);
    res.status(500).json({ error: `Internal: ${err?.message || err}` });
  }
});

export default router;
