// POST → transition pending_approval → approved.
// On approval: email each employee their pay stub via Resend.
import { NextResponse } from "next/server";
import { Resend } from "resend";
import { readAuth, db, ObjectId } from "../../../_auth";

const FROM = process.env.RESEND_PNGPAY_FROM_ADDRESS || process.env.RESEND_FROM_ADDRESS || "TeebeePay <noreply@curriculate.net>";
const resend = new Resend(process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY || "");

function stubHtml(co: any, period: any, emp: any, e: any) {
  const ccy = co.currency || "PGK";
  const lines = e.calc_breakdown?.allowance_lines || [];
  const postTax = e.calc_breakdown?.post_tax_deductions || [];
  return `<!doctype html><html><body style="font:14px/1.5 -apple-system,Segoe UI,Arial">
    <h2 style="margin:0">${escape(co.name)} — pay stub</h2>
    <p style="color:#555;margin:0 0 16px">Period ${period.period_start} to ${period.period_end} (paid ${period.pay_date})</p>
    <p><strong>${escape(emp.first_name)} ${escape(emp.last_name)}</strong></p>
    <table cellpadding="6" style="border-collapse:collapse;border:1px solid #ddd;min-width:360px">
      <tr><td>Hours</td><td align="right">${Number(e.hours).toFixed(2)}</td></tr>
      <tr><td>Gross</td><td align="right">${ccy} ${Number(e.gross).toFixed(2)}</td></tr>
      ${lines.map((l: any) => `<tr><td>+ ${escape(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      <tr><td>Salary/wages tax</td><td align="right">- ${ccy} ${Number(e.tax).toFixed(2)}</td></tr>
      <tr><td>Nasfund (6%)</td><td align="right">- ${ccy} ${Number(e.nasfund).toFixed(2)}</td></tr>
      ${postTax.map((l: any) => `<tr><td>- ${escape(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      ${Number(e.cash_advance) > 0 ? `<tr><td>Cash advance</td><td align="right">- ${ccy} ${Number(e.cash_advance).toFixed(2)}</td></tr>` : ""}
      <tr style="background:#f3f3f3;font-weight:600"><td>Net pay</td><td align="right">${ccy} ${Number(e.net).toFixed(2)}</td></tr>
    </table>
    ${e.note ? `<p style="margin-top:16px;padding:10px;background:#fffbe6;border-left:3px solid #f0c000"><b>Note:</b> ${escape(e.note)}</p>` : ""}
    ${co.payslip_message ? `<p style="margin-top:16px;color:#444">${escape(co.payslip_message)}</p>` : ""}
    <p style="color:#888;font-size:12px;margin-top:24px">Generated by TeebeePay.</p>
  </body></html>`;
}
function escape(s: any) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;","<": "&lt;",">": "&gt;",'"': "&quot;","'":"&#39;" }[c] as string));
}

export async function POST(req: Request, { params }: { params: Promise<{ pid: string }> }) {
  const u = readAuth(req);
  if (!u) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (u.clearance < 2) return NextResponse.json({ error: "Only bookkeeper+ can approve." }, { status: 403 });
  const { pid } = await params;
  try {
    const dbi = await db();
    const period: any = await dbi.collection("pay_periods").findOne({ _id: new ObjectId(pid) });
    if (!period) return NextResponse.json({ error: "Not found" }, { status: 404 });
    if (u.clearance < 3 && u.company_id !== period.company_id.toString()) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    if (period.status === "approved") return NextResponse.json({ ok: true, already: true });

    const company: any = await dbi.collection("companies").findOne({ _id: period.company_id });
    const entries: any[] = await dbi.collection("payroll_entries").find({ pay_period_id: period._id }).toArray();
    const emps: any[] = await dbi.collection("employees").find({ _id: { $in: entries.map((e) => e.employee_id) } }).toArray();
    const empMap = Object.fromEntries(emps.map((e) => [e._id.toString(), e]));

    const totalGross = entries.reduce((s, e) => s + (Number(e.gross) || 0), 0);
    const feesRaw: any[] = await dbi.collection("service_fees").find({ is_active: 1 }).toArray();
    const serviceFees = feesRaw.map((f) => ({
      name: f.name, pct: f.pct_of_gross,
      amount: r2(totalGross * (Number(f.pct_of_gross) || 0) / 100),
      account_no: f.account_no, account_name: f.account_name, branch_code: f.branch_code,
    }));

    await dbi.collection("pay_periods").updateOne({ _id: period._id }, {
      $set: { status: "approved", approved_by: u.uid, approved_at: new Date(),
        total_gross: r2(totalGross), service_fees: serviceFees },
    });

    let sent = 0, failed = 0;
    if (process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY) {
      for (const e of entries) {
        const emp = empMap[e.employee_id.toString()];
        if (!emp?.email) continue;
        try {
          await resend.emails.send({
            from: FROM, to: emp.email,
            subject: `${company.name} pay stub: ${period.period_start} to ${period.period_end}`,
            html: stubHtml(company, period, emp, e),
          });
          sent++;
        } catch (err) {
          console.error("[approve] stub send failed for", emp.email, err);
          failed++;
        }
      }
    }

    return NextResponse.json({ ok: true, totalGross: r2(totalGross), stubsSent: sent, stubsFailed: failed, serviceFees });
  } catch (e: any) {
    console.error("[teebeepay/approve] error:", e);
    return NextResponse.json({ error: e?.message || "Server error" }, { status: 500 });
  }
}

function r2(n: number) { return Math.round((n + Number.EPSILON) * 100) / 100; }
