// POST → re-send the pay stub email for a single entry.
import { NextResponse } from "next/server";
import { Resend } from "resend";
import { readAuth, db, ObjectId } from "../../../../../_auth";
import { logAudit } from "../../../../../_audit";

const FROM = process.env.RESEND_PNGPAY_FROM_ADDRESS || process.env.RESEND_FROM_ADDRESS || "TeebeePay <noreply@curriculate.net>";
const resend = new Resend(process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY || "");

function esc(s: any) {
  return String(s ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c] as string));
}

function stubHtml(co: any, period: any, emp: any, e: any) {
  const ccy = co.currency || "PGK";
  const lines = e.calc_breakdown?.allowance_lines || [];
  const post = e.calc_breakdown?.post_tax_deductions || [];
  const logoTag = co.logo_image
    ? `<img src="data:${co.logo_mime || "image/png"};base64,${co.logo_image}" alt="${esc(co.name)}" style="max-height:48px;display:block;margin-bottom:10px">`
    : "";
  return `<!doctype html><html><body style="font:14px/1.5 -apple-system,Segoe UI,Arial;color:#0f172a">
    ${logoTag}
    <h2 style="margin:0">${esc(co.name)} — pay stub</h2>
    <p style="color:#555;margin:0 0 16px">Period ${period.period_start} to ${period.period_end} (paid ${period.pay_date})</p>
    <p><strong>${esc(emp.first_name)} ${esc(emp.last_name)}</strong></p>
    <table cellpadding="6" style="border-collapse:collapse;border:1px solid #ddd;min-width:360px">
      <tr><td>Hours</td><td align="right">${Number(e.hours || 0).toFixed(2)}</td></tr>
      <tr><td>Gross</td><td align="right">${ccy} ${Number(e.gross || 0).toFixed(2)}</td></tr>
      ${lines.map((l: any) => `<tr><td>+ ${esc(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      <tr><td>Salary/wages tax</td><td align="right">- ${ccy} ${Number(e.tax || 0).toFixed(2)}</td></tr>
      <tr><td>Nasfund (6%)</td><td align="right">- ${ccy} ${Number(e.nasfund || 0).toFixed(2)}</td></tr>
      ${post.map((l: any) => `<tr><td>- ${esc(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      ${Number(e.cash_advance || 0) > 0 ? `<tr><td>Cash advance</td><td align="right">- ${ccy} ${Number(e.cash_advance).toFixed(2)}</td></tr>` : ""}
      <tr style="background:#f3f3f3;font-weight:600"><td>Net pay</td><td align="right">${ccy} ${Number(e.net || 0).toFixed(2)}</td></tr>
    </table>
    ${e.note ? `<p style="margin-top:16px;padding:10px;background:#fffbe6;border-left:3px solid #f0c000"><b>Note:</b> ${esc(e.note)}</p>` : ""}
    ${co.payslip_message ? `<p style="margin-top:16px;color:#444">${esc(co.payslip_message)}</p>` : ""}
    <p style="color:#888;font-size:12px;margin-top:24px;border-top:1px solid #eee;padding-top:10px">Generated by TeebeePay. Re-sent on ${new Date().toISOString().slice(0, 10)}.</p>
  </body></html>`;
}

export async function POST(req: Request, { params }: { params: Promise<{ pid: string; eid: string }> }) {
  const u = readAuth(req);
  if (!u) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (u.clearance < 2) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const { pid, eid } = await params;

  try {
    const dbi = await db();
    const period: any = await dbi.collection("pay_periods").findOne({ _id: new ObjectId(pid) });
    if (!period) return NextResponse.json({ error: "Not found" }, { status: 404 });
    if (u.clearance < 3 && u.company_id !== period.company_id.toString()) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const entry: any = await dbi.collection("payroll_entries").findOne({ _id: new ObjectId(eid), pay_period_id: period._id });
    if (!entry) return NextResponse.json({ error: "Entry not found" }, { status: 404 });
    const emp: any = await dbi.collection("employees").findOne({ _id: entry.employee_id });
    if (!emp) return NextResponse.json({ error: "Employee not found" }, { status: 404 });
    if (!emp.email) return NextResponse.json({ error: "This employee has no email on file." }, { status: 400 });

    const co: any = await dbi.collection("companies").findOne({ _id: period.company_id });
    if (!(process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY)) {
      return NextResponse.json({ error: "Email is not configured on the server." }, { status: 500 });
    }
    await resend.emails.send({
      from: FROM,
      to: emp.email,
      subject: `${co.name} pay stub: ${period.period_start} to ${period.period_end}`,
      html: stubHtml(co, period, emp, entry),
    });
    // Log the resend
    await dbi.collection("payroll_entries").updateOne({ _id: entry._id }, {
      $set: { last_resent_at: new Date(), last_resent_by: u.email },
      $inc: { resend_count: 1 },
    });
    await logAudit({
      actor_email: u.email, actor_kind: "user",
      action: "stub.resend",
      resource_type: "payroll_entry", resource_id: entry._id.toString(),
      company_id: period.company_id.toString(),
      details: { to: emp.email, period_id: period._id.toString() },
    });
    return NextResponse.json({ ok: true });
  } catch (e: any) {
    console.error("[teebeepay/resend] error:", e);
    return NextResponse.json({ error: e?.message || "Server error" }, { status: 500 });
  }
}
