// src/pages/TasksetListPage.jsx
import React, { useEffect, useState } from "react";
import api from "../api/client";

export default function TasksetListPage() {
  const [tasksets, setTasksets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    api
      .get("/tasksets/mine")
      .then((res) => setTasksets(res.data.tasksets || []))
      .catch((err) => {
        console.error(err);
        setError(
          err.response?.data?.error || "Unable to load saved tasksets."
        );
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="p-4">Loading tasksets…</div>;
  if (error) return <div className="p-4 text-red-600">{error}</div>;

  return (
    <div className="p-6 space-y-4">
      <header>
        <h1 className="text-2xl font-bold">My Tasksets</h1>
        <p className="text-sm text-gray-600">
          Saved, reusable tasksets generated by Curriculate.
        </p>
      </header>

      {tasksets.length === 0 && (
        <p className="text-sm text-gray-600">
          You have no saved tasksets yet. Generate one and click &quot;Save
          Taskset&quot; in the generator.
        </p>
      )}

      <div className="space-y-3">
        {tasksets.map((ts) => (
          <div
            key={ts._id}
            className="border rounded-lg bg-white p-3 flex items-center justify-between"
          >
            <div>
              <div className="font-semibold text-sm">{ts.name}</div>
              <div className="text-xs text-gray-500">
                {ts.tasks?.length || 0} tasks •{" "}
                {new Date(ts.createdAt).toLocaleString()}
              </div>
            </div>
            {/* You can add "Play" / "Edit" buttons here later */}
          </div>
        ))}
      </div>
    </div>
  );
}
