// Email via Resend. Falls back to writing .eml files into /data/outbox/
// if RESEND_API_KEY is missing — useful during development.
const fs = require('fs');
const path = require('path');

let resendClient = null;
function getClient() {
  if (resendClient) return resendClient;
  if (!process.env.RESEND_API_KEY) return null;
  const { Resend } = require('resend');
  resendClient = new Resend(process.env.RESEND_API_KEY);
  return resendClient;
}

function fmt(n) { return Number(n).toFixed(2); }
function currency(n, ccy) { return `${ccy || 'PGK'} ${fmt(n)}`; }

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
}

function stubHtml({ company, period, employee, hours, cash_advance, note, gross, tax, nasfund, other_deductions, net, breakdown }) {
  const lines = (breakdown && breakdown.custom_lines) || [];
  return `<!doctype html><html><body style="font:14px/1.5 -apple-system,Segoe UI,Arial">
  <h2 style="margin:0">${escapeHtml(company.name)} — pay stub</h2>
  <p style="color:#555;margin:0 0 16px">Period ${period.period_start} to ${period.period_end} (paid ${period.pay_date})</p>
  <p><strong>${escapeHtml(employee.first_name)} ${escapeHtml(employee.last_name)}</strong><br>
     ${escapeHtml(employee.bank_account_name || '')} ${employee.bank_account_no ? '· ' + escapeHtml(employee.bank_account_no) : ''}</p>
  <table cellpadding="6" style="border-collapse:collapse;border:1px solid #ddd;min-width:360px">
    <tr><td>Hours worked</td><td align="right">${fmt(hours)}</td></tr>
    <tr><td>Gross</td><td align="right">${currency(gross, company.currency)}</td></tr>
    <tr><td>Salary/wages tax</td><td align="right">- ${currency(tax, company.currency)}</td></tr>
    <tr><td>Nasfund (6%)</td><td align="right">- ${currency(nasfund, company.currency)}</td></tr>
    ${lines.map(l => `<tr><td>${escapeHtml(l.name)}</td><td align="right">- ${currency(l.amount, company.currency)}</td></tr>`).join('')}
    ${cash_advance > 0 ? `<tr><td>Cash advance</td><td align="right">- ${currency(cash_advance, company.currency)}</td></tr>` : ''}
    <tr style="background:#f3f3f3;font-weight:600"><td>Net pay</td><td align="right">${currency(net, company.currency)}</td></tr>
  </table>
  ${note ? `<p style="margin-top:16px;padding:10px;background:#fffbe6;border-left:3px solid #f0c000"><strong>Note from manager:</strong><br>${escapeHtml(note)}</p>` : ''}
  ${company.payslip_message ? `<p style="margin-top:16px;color:#444">${escapeHtml(company.payslip_message)}</p>` : ''}
  <p style="color:#888;font-size:12px;margin-top:24px">Generated by PNGPay.</p>
  </body></html>`;
}

function ensureOutbox() {
  const dir = path.join(__dirname, '..', 'data', 'outbox');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

async function sendOrSpool({ to, subject, html, text, attachments }) {
  const client = getClient();
  const from = process.env.EMAIL_FROM || 'PNGPay <onboarding@resend.dev>';
  if (client) {
    return client.emails.send({ from, to, subject, html, text, attachments });
  }
  const dir = ensureOutbox();
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safe = String(to).replace(/[^A-Za-z0-9_.-]/g, '_');
  const f = path.join(dir, `${stamp}__${safe}.eml`);
  const att = (attachments || []).map(a => `--- attachment: ${a.filename} ---\n${a.content}\n--- end ---\n`).join('');
  fs.writeFileSync(f, `To: ${to}\nFrom: ${from}\nSubject: ${subject}\n\n${html || text}\n\n${att}`);
  return { id: 'spooled:' + path.basename(f) };
}

async function sendPayStub(row) {
  const subject = `${row.company.name} pay stub: ${row.period.period_start} to ${row.period.period_end}`;
  return sendOrSpool({ to: row.employee.email, subject, html: stubHtml(row) });
}

async function sendCsvToAdmin({ company, csv, period }) {
  const { getDb } = require('./db');
  const db = getDb();
  const admins = await db.collection('users').find({
    company_id: company._id ? company._id : null,
    role: { $in: ['company_admin', 'super_admin'] },
    is_active: 1,
  }).toArray();
  const supers = await db.collection('users').find({ role: 'super_admin', is_active: 1 }).toArray();
  const all = Array.from(new Set([...admins, ...supers].map(u => u.email))).filter(Boolean);
  if (!all.length) return;
  const filename = `${(company.abbreviation || company.name).replace(/\W+/g, '_')}-${period.period_start}.csv`;
  for (const to of all) {
    await sendOrSpool({
      to, subject: `${company.name} payroll CSV ${period.period_start}`,
      html: `<p>Payroll CSV attached for period ${period.period_start} to ${period.period_end} (paid ${period.pay_date}).</p>`,
      attachments: [{ filename, content: Buffer.from(csv).toString('base64') }],
    });
  }
}

module.exports = { sendPayStub, sendCsvToAdmin, sendOrSpool };
