import mongoose from "mongoose";

const { Schema } = mongoose;

// Assessment categories used for deeper breakdown of AI / rubric scoring
const AssessmentCategorySchema = new Schema(
  {
    key: { type: String, required: true, trim: true }, // canonical ID e.g. "knowledge"
    label: { type: String, required: true, trim: true }, // human-readable name
    description: { type: String, default: "", trim: true },
    weight: { type: Number, default: 25 },
  },
  { _id: false }
);

const TeacherProfileSchema = new Schema(
  {
    // IMPORTANT: per-user profile binding
    ownerId: { type: String, required: true, index: true, unique: true },

    // Admin flags (optional but helpful)
    isAdmin: { type: Boolean, default: false },
    role: { type: String, default: "" }, // e.g. "admin"
    roles: { type: [String], default: [] }, // e.g. ["admin"]

    // Teacher or facilitator display name (used in some UIs)
    displayName: { type: String, default: "" },

    // Explicit presenter fields used in the TeacherApp UI
    presenterName: { type: String, default: "" },
    presenterRole: { type: String, default: "" },

    // NEW: canonical presenter title used by the TeacherProfile page
    presenterTitle: { type: String, default: "" },

    // Legacy "title" field – kept in sync with presenterTitle
    title: { type: String, default: "" },

    schoolName: { type: String, default: "" },

    // The email address where reports / transcripts get sent
    email: {
      type: String,
      required: false,
      default: "",
      lowercase: true,
      trim: true,
    },

    // TeacherApp access code (alphanumeric, generated by admin app)
    entryCode: { type: String, default: "", trim: true },

    // Optional separate report email (if ever used)
    reportEmail: {
      type: String,
      required: false,
      default: "",
      lowercase: true,
      trim: true,
    },

    // Subjects, grades, etc. — optional for non-school users
    gradesTaught: { type: [String], default: [] },
    subjectsTaught: { type: [String], default: [] },

    // Worldview / pedagogical "perspectives" multi-select
    perspectives: { type: [String], default: [] },

    // Whether AI / email reports should include per-student breakdowns
    includeIndividualReports: { type: Boolean, default: false },
    // Legacy alias – some code may still reference this
    includeStudentReports: { type: Boolean, default: false },

    // Optional global toggle for AI transcript / reporting tools
    aiTranscriptEnabled: { type: Boolean, default: true },

    // Whether to include a narrative session summary in reports
    includeSessionSummary: { type: Boolean, default: true },

    // Teacher preferences for AI task-set generator
    defaultGrade: { type: String, default: "" },
    defaultSubject: { type: String, default: "" },
    defaultDifficulty: {
      type: String,
      enum: ["EASY", "MEDIUM", "HARD"],
      default: "MEDIUM",
    },
    defaultDurationMinutes: { type: Number, default: 45 },
    defaultLearningGoal: {
      type: String,
      enum: ["REVIEW", "INTRODUCTION", "ENRICHMENT", "ASSESSMENT"],
      default: "REVIEW",
    },
    defaultNumTasks: { type: Number, default: 8 },
    defaultTaskTypes: { type: [String], default: [] },
    defaultStations: { type: Number, default: 8 },

    // ✅ Random Treats (your UI saves this)
    treatsPerSession: { type: Number, default: 2 },

    // ✅ Multi-room location labels (your UI saves this)
    locationOptions: { type: [String], default: ["Classroom"] },

    // When enabled, text-heavy tasks show a camera for paper-based work instead of on-screen input
    minimizeOnScreen: { type: Boolean, default: false },

    // ✅ Voice settings (your UI has these fields)
    voiceId: { type: String, default: "" },
    voiceSampleUrl: { type: String, default: "" },
    voiceClonedAt: { type: Date, default: null },
    preferredVoice: { type: String, default: "alloy" },

    // ✅ Jeopardy defaults (your UI saves these)
    jeopardyDefaultContestantCount: { type: Number, default: 3 },
    jeopardyDefaultAnswerMode: {
      type: String,
      enum: ["buzz-first", "all-try"],
      default: "buzz-first",
    },
    jeopardyAllowNegativeScores: { type: Boolean, default: true },
    jeopardyAllowRebound: { type: Boolean, default: true },

    // User-defined rubric categories for per-student breakdown
    assessmentCategories: { type: [AssessmentCategorySchema], default: [] },
  },
  { timestamps: true }
);

// Keep presenterTitle and title in sync at the model level whenever saved
TeacherProfileSchema.pre("save", function (next) {
  if (this.presenterTitle && !this.title) this.title = this.presenterTitle;
  if (this.title && !this.presenterTitle) this.presenterTitle = this.title;

  // Keep report flags in sync (for old code paths)
  if (typeof this.includeIndividualReports === "boolean") {
    this.includeStudentReports = this.includeIndividualReports;
  } else if (typeof this.includeStudentReports === "boolean") {
    this.includeIndividualReports = this.includeStudentReports;
  }

  next();
});

const TeacherProfile =
  mongoose.models.TeacherProfile ||
  mongoose.model("TeacherProfile", TeacherProfileSchema);

export default TeacherProfile;
