// frontend/src/app/api/teebeepay/approve-via-email/route.ts
//
// Public endpoint — no auth header needed. Authenticates via the
// signed approval token from the email link.
//
// GET  ?t=<token> → returns the period summary so the public page can render it
// POST { token }   → performs approval (idempotent; subsequent calls return already-approved)
import { NextResponse } from "next/server";
import { Resend } from "resend";
import { db, ObjectId, readApprovalToken, ROLE_CLEARANCE } from "../_auth";
import { logAudit } from "../_audit";

const FROM = process.env.RESEND_PNGPAY_FROM_ADDRESS || process.env.RESEND_FROM_ADDRESS || "TeebeePay <noreply@curriculate.net>";
const resend = new Resend(process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY || "");

function esc(s: any) {
  return String(s ?? "").replace(/[&<>"']/g, (c: string) => ({ "&": "&amp;","<": "&lt;",">": "&gt;",'"': "&quot;","'":"&#39;" }[c] as string));
}
function stubHtml(co: any, period: any, emp: any, e: any) {
  const ccy = co.currency || "PGK";
  const lines = e.calc_breakdown?.allowance_lines || [];
  const post = e.calc_breakdown?.post_tax_deductions || [];
  const logoTag = co.logo_image
    ? `<img src="data:${co.logo_mime || "image/png"};base64,${co.logo_image}" alt="${esc(co.name)}" style="max-height:54px;display:block;margin-bottom:12px">`
    : "";
  return `<!doctype html><html><body style="font:14px/1.5 -apple-system,Segoe UI,Arial">
    ${logoTag}
    <h2 style="margin:0">${esc(co.name)} — pay stub</h2>
    <p style="color:#555;margin:0 0 16px">Period ${period.period_start} to ${period.period_end} (paid ${period.pay_date})</p>
    <p><strong>${esc(emp.first_name)} ${esc(emp.last_name)}</strong></p>
    <table cellpadding="6" style="border-collapse:collapse;border:1px solid #ddd;min-width:360px">
      <tr><td>Hours</td><td align="right">${Number(e.hours || 0).toFixed(2)}</td></tr>
      <tr><td>Gross</td><td align="right">${ccy} ${Number(e.gross || 0).toFixed(2)}</td></tr>
      ${lines.map((l: any) => `<tr><td>+ ${esc(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      <tr><td>Salary/wages tax</td><td align="right">- ${ccy} ${Number(e.tax || 0).toFixed(2)}</td></tr>
      <tr><td>Nasfund (6%)</td><td align="right">- ${ccy} ${Number(e.nasfund || 0).toFixed(2)}</td></tr>
      ${post.map((l: any) => `<tr><td>- ${esc(l.name)}</td><td align="right">${ccy} ${Number(l.amount).toFixed(2)}</td></tr>`).join("")}
      ${Number(e.cash_advance || 0) > 0 ? `<tr><td>Cash advance</td><td align="right">- ${ccy} ${Number(e.cash_advance).toFixed(2)}</td></tr>` : ""}
      <tr style="background:#f3f3f3;font-weight:600"><td>Net pay</td><td align="right">${ccy} ${Number(e.net || 0).toFixed(2)}</td></tr>
    </table>
    ${e.note ? `<p style="margin-top:16px;padding:10px;background:#fffbe6;border-left:3px solid #f0c000"><b>Note:</b> ${esc(e.note)}</p>` : ""}
    ${co.payslip_message ? `<p style="margin-top:16px;color:#444">${esc(co.payslip_message)}</p>` : ""}
    <p style="color:#888;font-size:12px;margin-top:24px">Generated by TeebeePay.</p>
  </body></html>`;
}
function r2(n: number) { return Math.round((n + Number.EPSILON) * 100) / 100; }

async function loadPeriodForToken(tok: string) {
  const payload = readApprovalToken(tok);
  if (!payload) return { error: "Link is invalid or expired.", status: 401 };
  const dbi = await db();
  const p: any = await dbi.collection("pay_periods").findOne({ _id: new ObjectId(payload.pid) });
  if (!p) return { error: "Pay period not found.", status: 404 };
  const co: any = await dbi.collection("companies").findOne({ _id: p.company_id });
  const entries: any[] = await dbi.collection("payroll_entries").find({ pay_period_id: p._id }).toArray();
  return { dbi, payload, period: p, company: co, entries };
}

export async function GET(req: Request) {
  const u = new URL(req.url);
  const tok = u.searchParams.get("t") || "";
  const r = await loadPeriodForToken(tok);
  if ("error" in r) return NextResponse.json({ error: r.error }, { status: r.status });
  const totals = r.entries.reduce((a, e) => ({
    gross: a.gross + (e.gross || 0), tax: a.tax + (e.tax || 0),
    nasfund: a.nasfund + (e.nasfund || 0), net: a.net + (e.net || 0),
  }), { gross: 0, tax: 0, nasfund: 0, net: 0 });
  return NextResponse.json({
    ok: true,
    approver_email: r.payload.email,
    period: {
      id: r.period._id.toString(),
      period_start: r.period.period_start, period_end: r.period.period_end, pay_date: r.period.pay_date,
      status: r.period.status, approved_at: r.period.approved_at || null,
    },
    company: { name: r.company.name, currency: r.company.currency || "PGK" },
    n_entries: r.entries.length,
    totals,
  });
}

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({} as any));
  const tok = String(body.token || body.t || "");
  const action = String(body.action || "approve");
  const r = await loadPeriodForToken(tok);
  if ("error" in r) return NextResponse.json({ error: r.error }, { status: r.status });
  const { dbi, payload, period, company, entries } = r;

  if (action === "reject") {
    if (period.status === "approved") return NextResponse.json({ error: "Already approved." }, { status: 409 });
    await dbi.collection("pay_periods").updateOne({ _id: period._id }, {
      $set: { status: "draft", rejected_at: new Date(), rejected_by: payload.email,
              rejection_reason: String(body.reason || "").slice(0, 1000) || null },
    });
    await logAudit({
      actor_email: payload.email, actor_kind: "approval_link",
      action: "payroll.reject",
      resource_type: "pay_period", resource_id: period._id.toString(),
      company_id: period.company_id.toString(),
      details: { reason: String(body.reason || "").slice(0, 200) || null, via: "email_magic_link" },
    });
    return NextResponse.json({ ok: true, status: "draft" });
  }

  if (period.status === "approved") {
    return NextResponse.json({ ok: true, already: true });
  }

  // Approve and dispatch pay stubs (same logic as the normal approve route)
  const totalGross = entries.reduce((s, e) => s + (Number(e.gross) || 0), 0);
  const fees: any[] = await dbi.collection("service_fees").find({ is_active: 1 }).toArray();
  const serviceFees = fees.map((f) => ({
    name: f.name, pct: f.pct_of_gross,
    amount: r2(totalGross * (Number(f.pct_of_gross) || 0) / 100),
    account_no: f.account_no, account_name: f.account_name, branch_code: f.branch_code,
  }));

  await dbi.collection("pay_periods").updateOne({ _id: period._id }, {
    $set: { status: "approved", approved_via: "email_magic_link",
            approved_by_email: payload.email, approved_at: new Date(),
            total_gross: r2(totalGross), service_fees: serviceFees },
  });

  // Dispatch stubs
  const emps: any[] = await dbi.collection("employees").find({ _id: { $in: entries.map((e) => e.employee_id) } }).toArray();
  const empMap = Object.fromEntries(emps.map((e) => [e._id.toString(), e]));
  let sent = 0, failed = 0;
  if (process.env.RESEND_PNGPAY_API_KEY || process.env.RESEND_API_KEY) {
    for (const e of entries) {
      const emp = empMap[e.employee_id.toString()];
      if (!emp?.email) continue;
      try {
        await resend.emails.send({
          from: FROM, to: emp.email,
          subject: `${company.name} pay stub: ${period.period_start} to ${period.period_end}`,
          html: stubHtml(company, period, emp, e),
        });
        sent++;
      } catch { failed++; }
    }
  }

  await logAudit({
    actor_email: payload.email, actor_kind: "approval_link",
    action: "payroll.approve",
    resource_type: "pay_period", resource_id: period._id.toString(),
    company_id: period.company_id.toString(),
    details: { entries: entries.length, totalGross: r2(totalGross), stubsSent: sent, stubsFailed: failed, via: "email_magic_link" },
  });

  return NextResponse.json({
    ok: true, status: "approved", totalGross: r2(totalGross),
    stubsSent: sent, stubsFailed: failed, serviceFees,
  });
}
